stages:
  - build
  - publish

variables:
  GO_TIMEOUT: "20s"
  TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA


build:
  stage: build
  image: golang:latest
  script:
    - ALL_PACKAGES=$(go list ./... | grep -v -E "vendor")
    - go test -timeout $GO_TIMEOUT -v $ALL_PACKAGE
    - go build -o /bin/counter-service
  artifacts:
    paths:
      - scripts

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --tag $TAG_COMMIT --tag $TAG_LATEST --build-arg http_port=8080 .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

